from enum import Enum

class ApplicationStatus(str, Enum):
    DRAFT = "DRAFT"
    KYC_PENDING = "KYC_PENDING"
    KYC_COMPLETED = "KYC_COMPLETED"
    CREDIT_CHECK_PENDING = "CREDIT_CHECK_PENDING"
    CREDIT_CHECK_COMPLETED = "CREDIT_CHECK_COMPLETED"
    ELIGIBLE = "ELIGIBLE"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
